### ISSUE TITLE
yt-dlp-FixupMtimeが、yt-dlpが参照するプラグインパスにインストールされない

### ISSUE THREAD

**Issue by cradle8810** [cradle8810/ansible_hayaworld#297]
もともとのエラーは次のとおり。
```
Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 17, in <module>
  File "yt_dlp/__init__.py", line 1086, in main
  File "yt_dlp/__init__.py", line 984, in _real_main
  File "yt_dlp/YoutubeDL.py", line 809, in __init__
  File "yt_dlp/postprocessor/__init__.py", line 42, in get_postprocessor
KeyError: 'FixupMtimePP'
[PYI-181804:ERROR] Failed to execute script '__main__' due to unhandled exception!
```

これは、yt-dlp-FixupMtimeのREADMEのとおり、pipでインストールした場合のインストール先ディレクトリが、今のyt-dlpのバージョンでは正しくないため。yt-dlpが参照するパス配下にインストールされない。

```
skylark.hayaworld.home[~]% find . -name 'yt_dlp_plugins'
./.local/lib/python3.10/site-packages/yt_dlp_plugins

HayabookAir2023.hayaworld.home[~]% find . -name 'yt_dlp_plugins'
./Library/Python/3.9/lib/python/site-packages/yt_dlp_plugins
```

プラグインとして参照するディレクトリは下記のとおり。
https://github.com/yt-dlp/yt-dlp#installing-plugins

めんどっちいことにpythonのバージョンがディレクトリ名に入るため、pythonのバージョンを確認のうえ、
`~/.yt-dlp/plugins/`配下に、`~/.local/lib/python3.(バージョン)/site-packages/yt_dlp_plugins`へのシンボリックリンクを作成するのがいいかもしれない

**Comment by cradle8810** [comment]
```
HayabookAir2023.hayaworld.home[~]% pip3 show -v yt-dlp-FixupMtime | grep Location
Location: /Users/hayato/Library/Python/3.9/lib/python/site-packages

skylark.hayaworld.home[~]% pip3 show -v yt-dlp-FixupMtime | grep Location
Location: /home/hayato/.local/lib/python3.10/site-packages
```

インストール先は上記のコマンドでとれるので、前段に置くとよい

**Comment by cradle8810** [comment]
Linuxの場合は下記のコマンドに相当する
```
% mkdir -p ~/.yt-dlp/plugins/yt-dlp-FixupMtime/yt_dlp_plugins
% ln -s ~/.local/lib/python3.10/site-packages/yt_dlp_plugins/postprocessor ~/.yt-dlp/plugins/yt-dlp-FixupMtime/yt_dlp_plugins
```

**Comment by cradle8810** [comment]
Ubuntu24.04ではここ。
```
/usr/local/lib/python3.12/dist-packages/yt_dlp_plugins/postprocessor/fixup_mtime.py
```

前段にPythonのバージョンを確認するtaskを入れたほうがよさそう

**Comment by cradle8810** [comment]
`ansible_python_version`というfactsがある。システムに直接yt-dlpをインストールしているので、バージョンは同一と考えて差し支えなさそう

**Comment by cradle8810** [comment]
#343
